services:
  - type: web
    name: invitation-face-detection
    runtime: docker
    branch: main
    buildCommand: docker build -t invitation-app .
    startCommand: docker run -p 5000:5000 invitation-app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: GUNICORN_WORKERS
        value: "2"
    healthCheckPath: /
    autoDeploy: true
    plan: free
