services:
  - type: web
    name: invitation-app
    env: docker
    buildCommand: docker build -t invitation-app .
    startCommand: docker run -p 5000:5000 invitation-app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 5000
