services:
  - type: web
    name: invitation-app
    env: python
    buildCommand: cd src && pip install -r requirements.txt
    startCommand: cd src && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
